name: Benchmark

on:
  push:
      branches: [devel]
  pull_request:

jobs:
  snapshotter:
    name: "Snapshotter"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install nerdctl
        run: |
          VERSION="1.7.7"  # Set the version you want to install
          curl -LO https://github.com/containerd/nerdctl/releases/download/v$VERSION/nerdctl-$VERSION-linux-amd64.tar.gz
          tar Cxzvvf /usr/local nerdctl-full-$VERSION-linux-amd64.tar.gz
          sudo systemctl enable --now containerd
      
      - name: Configure cvmfs-snapshotter
          cd snapshotter
          make
          cp out/cvmfs_snapshotter /usr/local/bin/cvmfs_snapshotter
          cp config/etc/systemd/system/cvmfs-snapshotter.service /etc/systemd/system/
          mkdir -p /etc/containerd-cvmfs-grpc && touch /etc/containerd-cvmfs-grpc/config.toml
          sudo tee /etc/containerd/config.toml > /dev/null <<EOL
          version = 2

          [plugins."io.containerd.grpc.v1.cri".containerd]
              snapshotter = "cvmfs-snapshotter"
              disable_snapshot_annotations = false

          [proxy_plugins]
              [proxy_plugins.cvmfs-snapshotter]
                  type = "snapshot"
                  address = "/run/containerd-cvmfs-grpc/containerd-cvmfs-grpc.sock"
          EOL
          

      - name: Run benchmark
        run: python3 snapshotter/benchmark.py

